---
name: Rerun failed testing farm tests
on:
  issue_comment:
    types:
      - created
permissions:
  contents: read
jobs:
  retest:
    if: |
      github.event.issue.pull_request
      && github.event.comment.body == '[citest_bad]'
    permissions:
      actions: write # for re-running failed jobs: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run
    runs-on: ubuntu-latest
    steps:
      - name: Re-run failed jobs for this PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_TITLE: ${{ github.event.issue.title }}
        run: |
          RUN_ID=$(gh api "repos/$REPO/actions/workflows/tft.yml/runs?event=issue_comment" \
            | jq -r '[.workflow_runs[] | select( .conclusion == "failure" ) | select ( .display_title="$PR_TITLE" ) | .id][0]')
          gh api --method POST repos/$REPO/actions/runs/$RUN_ID/rerun-failed-jobs
